# Generated by Django 2.1 on 2018-08-22 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180818_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerperuser',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerperuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videopercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videopercategory',
            name='video',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='videos',
            field=models.ManyToManyField(to='polls.Video'),
        ),
        migrations.DeleteModel(
            name='AnswerPerUser',
        ),
        migrations.DeleteModel(
            name='VideoPerCategory',
        ),
    ]
